=== matthewmoorcroft/Java-Image-Lang-Compiler/Ejercicios/option.dtd
<!ELEMENT libreria (pelicula +)>
<!ELEMENT pelicula (titulo, director, año, duracion, actores, genero +, nacionalidad +)>
<!ATTLIST pelicula id ID #REQUIRED>
<!ELEMENT actores ((actor, personaje *)+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT personaje (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>

=== matthewmoorcroft/Java-Image-Lang-Compiler/Ejercicios/prac2.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE libreria SYSTEM "option.dtd">
<libreria>
  <pelicula id="1">
    <director>Maria</director>
    <año>2018</año>
    <duracion>120</duracion>
    <actores>
      <actor>Matt</actor>
    </actores>
    <genero>Drama</genero>
    <nacionalidad>Española</nacionalidad>
  </pelicula>
</libreria>
