=== matthewmoorcroft/Java-Image-Lang-Compiler/Ejercicios/Ejercicio3/DTDCatalogo.dtd
<!ELEMENT Catalogo (Pelicula)*>

<!ELEMENT Pelicula (Director|Actor|Genero|Nacionalidad)*>
	<!ATTLIST Pelicula
		Titulo ID #REQUIRED
		Duracion CDATA #IMPLIED
		Año CDATA #IMPLIED
	>
	
	
<!ELEMENT Actor EMPTY>
	<!ATTLIST Actor
		Nombre CDATA #IMPLIED
		Apellido CDATA #REQUIRED
		Profesion CDATA #FIXED "Actor"
	>
	
<!ELEMENT Director EMPTY>
	<!ATTLIST Director
		Nombre CDATA #IMPLIED
		Apellido CDATA #REQUIRED
		Profesion CDATA #FIXED "Director"
	>
	
<!ELEMENT Genero (#PCDATA)>
<!ELEMENT Nacionalidad (#PCDATA)>

=== matthewmoorcroft/Java-Image-Lang-Compiler/XML/lab3/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Catalogo SYSTEM "DTDCatalogo.dtd">

<Catalogo>

	<!--<Pelicula Titulo="" Anyo="" Duracion="">
		<Director Nombre ="" Apellido=""></Director>
		<Actor Nombre ="" Apellido="" ></Actor>
		<Genero> <![CDATA []]> </Genero>
		<Nacionalidad> <![CDATA []]> </Nacionalidad>
	</Pelicula>-->
	
	<Pelicula Titulo=" HarryPotter " Año="2001" Duracion="120">
		<Director Nombre ="Pepe" Apellido="Holis"></Director>
		<Actor Nombre ="Daniel" Apellido="Raciffle" ></Actor>
		<Genero> "Infantil" </Genero>
		<Nacionalidad> EEUU </Nacionalidad>
	</Pelicula>
	<Pelicula Titulo="HoliHolu " Año="2014" Duracion="2">
		<Director Nombre ="Vero" Apellido="Sabina"></Director>
		<Actor Nombre ="Marina" Apellido="Parrado" ></Actor>
		<Genero> "Patines" </Genero>
		<Nacionalidad> Sp </Nacionalidad>
	</Pelicula>
	<Pelicula Titulo="Peli sin nada mas que titulo"></Pelicula>


</Catalogo>
